mini_CRM/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView

from .views import IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path(r'profile/', include(
        ('users.urls', 'profile')
    )),

    path(r'customer_info/', include(
        ('customer_info.urls', 'customer_info')
    )),

    path(r'do_projects/', include(
        ('do_projects.urls', 'do_projects')
    )),

    path(r'cooperation/', include(
        ('cooperation.urls', 'cooperation')
    )),

    path(r'profile/', include(
        ('users.urls', 'users')
    )),



    # path('', RedirectView.as_view(url='/customer_info/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add Django site authentication urls (for login, logout, password management)
# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

# Only add this when we in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *


urlpatterns = [
    path('managers/', UserListView.as_view(), name='list'),
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('profile/', profile, name='profile'),
    # path('profile/', ProfileFormView.as_view(), name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

customer_info/models.py
from django.db import models

from ckeditor.fields import RichTextField


class Company(models.Model):
    name_company = models.CharField(max_length=200)  # Названия компании
    name = models.CharField(max_length=255)  # ФИО руководителя (контактного лица)
    # description = models.TextField()  # Краткого описания, которое заполняется в WYSIWYG редакторе
    description = RichTextField(blank=True, null=True)  # Краткого описания, которое заполняется в WYSIWYG редакторе
    created_date = models.DateField(auto_now_add=True)  # Даты создания записи
    change_date = models.DateTimeField(auto_now=True)  # Даты изменения записи
    address = models.CharField(max_length=254)  # Адрес
    phone_number = models.ManyToManyField('PhoneNumber')  # Телефон (несколько); +38-(0__)-__-___-__
    e_mail = models.ManyToManyField('Email')  # E-mail (несколько);

    class Meta:
        ordering = ['name_company']
        verbose_name_plural = 'Customer`s'

    def __str__(self):
        return f'{self.name_company}; {self.created_date}; {self.description[:60:]}'


class PhoneNumber(models.Model):
    phone_number = models.CharField(max_length=13)

    def __str__(self):
        return self.phone_number


class Email(models.Model):
    e_mail = models.EmailField()

    def __str__(self):
        return self.e_mail

do_projects/models.py
from django.db import models

from ckeditor.fields import RichTextField
from customer_info.models import Company


class DoProject(models.Model):
    name_project = models.CharField(max_length=200)
    description = RichTextField(blank=True, null=True)
    start_date = models.DateField(null=False)
    end_date = models.DateField(null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['name_project']

    def __str__(self):
        return self.name_project

templates/includes/header.html
<header class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="/admin/">Dj_Admin</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent2">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>

                {% if perms.customer_info.view_company %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'customer_info:list' %}" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Company</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'customer_info:list' %}">Company</a></li>

                            {% if perms.do_projects.add_company %}
                                <li><a class="dropdown-item" href="{% url 'customer_info:create' %}">create</a></li>
                            {% endif %}

                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Company_filter</a></li>
                        </ul>
                    </li>
                {% endif %}

                {% if perms.do_projects.view_doproject %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">do_project</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'do_projects:list' %}">Project</a></li>

                            {% if perms.do_projects.add_doproject %}
                                <li><a class="dropdown-item" href="{% url 'do_projects:create' %}">create</a></li>
                            {% endif %}

                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Project_filter</a></li>
                        </ul>
                    </li>
                {% endif %}

                {% if user.is_authenticated and perms.customer_info.view_author %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Cooperation</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'cooperation:list' %}">Cooperation</a></li>
                            <li><a class="dropdown-item" href="{% url 'cooperation:create' %}">create</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item disabled" href="#">Manager_filter</a></li>
                        </ul>
                    </li>
                {% endif %}

                {% if user.is_authenticated and perms.customer_info.view_author %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'users:list' %}">user_manager</a>
                    </li>

                {% endif %}

            </ul>
        </div>
    </div>
</header>